#+OPTIONS: tex:t
#+setupfile: info/index-bigblow-header.setup
#+include: info/common-header.org
#+Title: レポートについて

#+property: header-args:R :session *rtext* :results output :exports both

* 1回目のレポート

** 提出

- 〆切: 2022.06.01
- 提出場所: Webclass

** 問題

[[http://whitewell.sakura.ne.jp/R/Rprobability.html][Rで確率を学ぶ]] (白井) の演習問題より

*** 演習問題1-3: 
事象AとBに対し、次の式が成り立つことを示せ:

\( P(B | A) = P(B) P(A|B) / P(A) \)

*** 演習問題1-4: 

形状も重さも同じである赤球と白玉がそれぞれ50個ずつある箱から目をつぶっ
て一個取り出してそれが赤球である確率はいくらか。

次に、赤球を10個だけ入れた箱を3箱、赤球10個と白球10個を入れた箱を1箱、
赤球10個と白球40個を入れた箱を1箱、合計5箱用意したとする。 そして、ま
ず目をつぶって箱を選び、そこから目をつぶって玉を一個取り出し、それが赤
球であった場合の確率を求めよ。

そして、 先の操作での答と値が違うことを確認せよ。 最初の操作と次の操作
では共に赤球と白玉は50個ずつであったが、どうして2回の操作で確率が異な
るのか、説明せよ。

*** 習問題2-1
ある病気に罹患しているかどうか検査において、「（ある人が）陽性反応が出
る」という事象をAとし、「（その人が）実際に罹患しえいる」という事象をE
とする。 そして、確率が次のように与えられているとする:

\( P(A|E) = 0.56\), \( P(A|E^{c} ) = 0.04\), \(P(E)=0.035\).

この時、検査で陽性反応である確率と、陽性反
応が出た時に実際に病気を発病する確率をそれぞれ求めよ。


*** 演習問題2-2

とある適性検査で、（ある人が）適性と判定される事象をTとし、（その人が）
実際に適性があるという事象をEとする。

\( P(E)=0.60\), \( P(T|E)=0.80 \), \( P(T|E^{c})=0.040 \)のとき、

ある人が適性と判定され、かつ実際に適性である事象の確率を求めよ。

*** 演習問題2-3

三種類の物体(仮にA,B,C とする) の認識ができるカメラ機構を備えているロ
ボットがある。

ロボットは、
  - Aの物体を認識した場合には赤色のLEDを、
  - Bの物体を認識した場合は緑色のLED を、
  - C の物体を認識したら青のLED を点滅させる。
  - ロボットのカメラ機構は故障することがあり、故障した場合も
    ロボットは赤色のLEDを点滅させる。
  - そして故障する事前確率はp = 0.01 である。

ここで3 種類の物体の中からN 個をランダムに選び、次々にロボットに
提示した。すると、すべてロボットは赤色のLED を点滅させた。

N = 1 から N=10 の場合に対し、ロボットのカメラ機構が
壊れている確率を求めよ。
